import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createRoot } from 'react-dom/client';
import { createBrowserRouter, createRoutesFromElements, Route, RouterProvider } from 'react-router-dom';
import { Provider } from 'react-redux';
import { GoogleOAuthProvider } from '@react-oauth/google'; // ✅ Move GoogleOAuthProvider here
import store from './app/store';
import App from './App';
import AdminRoute from './general/components/routes/AdminRoute';
import CompanyEditingRoute from './general/components/routes/CompanyEditingRoute';
import PrivateRoute from './general/components/routes/PrivateRoute';
import HomeScreen from './general/screens/HomeScreen';
import LoginScreen from './features/auth/LoginScreen';
import RegisterScreen from './features/auth/RegisterScreen';
import ProductsScreen from './features/products/ProductsScreen';
import ProductScreen from './features/products/ProductScreen';
import ProfileScreen from './features/profile/ProfileScreen';
import ForgotPasswordScreen from './features/auth/ForgotPasswordScreen';
import AdminScreen from './features/company/AdminScreen';
import AdminProductPageScreen from './features/products/AdminProductPageScreen';
import AdminProductEditScreen from './features/products/AdminProductEditScreen';
import AdminUserListScreen from './features/users/AdminUserListScreen';
import AdminUserEditScreen from './features/users/AdminUserEditScreen';
import AdminJobsLists from './features/company/jobs/AdminJobsLists';
import AdminEditJob from './features/company/jobs/AdminEditJob';
import AdminEditCompanyInfo from "./features/company/companyInfo/edit-pages-screens/AdminEditCompanyInfo";
import AdminEditWebsiteStyles from "./features/websiteStyles/AdminEditWebsiteStyles";
import AdminEditHomePage from "./features/company/companyInfo/edit-pages-screens/AdminEditHomePage";
import AdminEditAboutUs from "./features/company/companyInfo/edit-pages-screens/AdminEditAboutUs";
import AdminEditServices from "./features/company/companyInfo/edit-pages-screens/AdminEditServices";
import AdminEditContactUs from "./features/company/companyInfo/edit-pages-screens/AdminEditContactUs";
import AboutUsScreen from './features/company/AboutUsScreen';
import ServicesScreen from './features/company/ServicesScreen';
import CareersScreen from './features/company/jobs/CareersScreen';
import ContactUsScreen from './features/company/ContactUsScreen';
import AdminCreateUsersScreen from './features/users/AdminCreateUsersScreen';
import AdminViewUserScreen from './features/users/AdminCreateUsersScreen';
import './App.css';
const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID;
const router = createBrowserRouter(createRoutesFromElements(_jsxs(Route, { path: "/", element: _jsx(App, {}), children: [_jsx(Route, { index: true, path: "/", element: _jsx(HomeScreen, {}) }), _jsx(Route, { path: "/product", element: _jsx(ProductsScreen, {}) }), _jsx(Route, { path: "/product/:pageNumber", element: _jsx(ProductsScreen, {}) }), _jsx(Route, { path: "/product/:id", element: _jsx(ProductScreen, {}) }), _jsx(Route, { path: "/login", element: _jsx(LoginScreen, {}) }), _jsx(Route, { path: "/register", element: _jsx(RegisterScreen, {}) }), _jsx(Route, { path: "/about", element: _jsx(AboutUsScreen, {}) }), _jsx(Route, { path: "/service", element: _jsx(ServicesScreen, {}) }), _jsx(Route, { path: "/job", element: _jsx(CareersScreen, {}) }), _jsx(Route, { path: "/contact", element: _jsx(ContactUsScreen, {}) }), _jsxs(Route, { path: "", element: _jsx(PrivateRoute, {}), children: [_jsx(Route, { path: "/profile", element: _jsx(ProfileScreen, {}) }), _jsx(Route, { path: "/forgot-password", element: _jsx(ForgotPasswordScreen, {}) }), _jsx(Route, { path: "/reset-password/:id", element: _jsx(ForgotPasswordScreen, {}) })] }), _jsxs(Route, { path: "", element: _jsx(AdminRoute, {}), children: [_jsx(Route, { path: "/admin", element: _jsx(AdminScreen, {}) }), _jsx(Route, { path: "/admin/productlist", element: _jsx(AdminProductPageScreen, {}) }), _jsx(Route, { path: "/admin/productlist/:pageNumber", element: _jsx(AdminProductPageScreen, {}) }), _jsx(Route, { path: "/admin/product/:id/edit", element: _jsx(AdminProductEditScreen, {}) }), _jsx(Route, { path: "/admin/userlist", element: _jsx(AdminUserListScreen, {}) }), _jsx(Route, { path: "/admin/user/:id", element: _jsx(AdminUserEditScreen, {}) }), _jsx(Route, { path: "/admin/user/:id/edit", element: _jsx(AdminUserEditScreen, {}) }), _jsx(Route, { path: "/admin/user/:id", element: _jsx(AdminViewUserScreen, {}) }), _jsx(Route, { path: "/admin/joblist", element: _jsx(AdminJobsLists, {}) }), _jsx(Route, { path: "/admin/job/:id/edit", element: _jsx(AdminEditJob, {}) }), _jsx(Route, { path: "/admin/users/create", element: _jsx(AdminCreateUsersScreen, {}) })] }), _jsxs(Route, { path: "", element: _jsx(CompanyEditingRoute, {}), children: [_jsx(Route, { path: "/admin/edit/homepage", element: _jsx(AdminEditHomePage, {}) }), _jsx(Route, { path: "/admin/edit/company-info", element: _jsx(AdminEditCompanyInfo, {}) }), _jsx(Route, { path: "/admin/edit/website-styles", element: _jsx(AdminEditWebsiteStyles, {}) }), _jsx(Route, { path: "/admin/edit/aboutpage", element: _jsx(AdminEditAboutUs, {}) }), _jsx(Route, { path: "/admin/edit/services", element: _jsx(AdminEditServices, {}) }), _jsx(Route, { path: "/admin/edit/contactpage", element: _jsx(AdminEditContactUs, {}) })] })] })));
console.log('google cli id: ', GOOGLE_CLIENT_ID);
createRoot(document.getElementById('root')).render(_jsx(GoogleOAuthProvider, { clientId: GOOGLE_CLIENT_ID, children: _jsx(Provider, { store: store, children: _jsx(RouterProvider, { router: router }) }) }));
